version: '3'
services:
  backend:
    container_name: graphql-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
  frontend:
    container_name: react-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
