version: '3'
services:
  backend:
    container_name: graphql-backend
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: always
    environment:
      NODE_ENV: production
      PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - type: volume
        source: backend-volume
        target: /app
volumes:
  backend-volume: