version: '3'
services:
  backend:
    container_name: graphql-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./backend
        target: /app
      - /app/node_modules
  frontend:
    container_name: react-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    ports:
      - "5173:5173"
    volumes:
      - type: bind
        source: ./frontend
        target: /app
      - /app/node_modules
